- README.md
> Adding Volumio to the OS Images List

- README.md
Note: Lakka does not have an HTTPS URL, so the standard HTTP one was used.
> Add Recalbox and Lakka to the list of OS Images.

- README.md
> Fix typo: Manifestio > Manifesto

- README.md
> Add PiShrink to tools

- README.md
> Add smart mirror to projects

- README.md
> Add MagicMirror.

- README.md
> added doorbot project

- README.md
> Add Jasper (open source personal assistant) to projects section

- README.md
> Add guide to program a rpi0 over USB

- README.md
I have added a couple of links to some blog posts I wrote on the topic of Raspberry Pis 😄 
> Add resource links

- README.md
> Add RasPlex to OS Images

- README.md
- [ X] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [X ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [X ] includes a valid (https) link,
- [X ] includes a concise and on-topic description,
- [X ] mentions if there is only support some devices,
- [X ] is not a duplicate,
- [ X] has been added at the bottom of the appropriate category,
- [ X] is in the form of **Named Link - Description, seperated by commas.**
- [X ] ends with a dot.
> Lightberry project added to the list

- README.md
> Add chilipie-kiosk image

- README.md
> Add SecPi to projects section

- README.md
> Add PiClock to projects section

- README.md
Adding a project to be able to control your garage door using a Raspberry Pi and a Android app and create a one time pin to give authorised people one time access.
> Adding Raspberry Pi Garage Door Opener project

- README.md
- Small, designed to fit 2GB SD cards
- Auto-expands to full size of SD card on boot
- Lots of pre-boot editable settings (can be modified on Windows, even)
- Lots of configurable scripts, equally as easy to set up
Only image I use, now.
> Added DietPi image

- README.md
> Add project Movel to README.md

- README.md
> Add CentOS image

- README.md
> Add PiFanTuner project

- README.md
> Added SkyJack (drone exploitation)

- README.md
Minibian and media server resources link
> Add Minibian and Media Server Guides

- README.md
> Add Nerves Project

- README.md
> Added berryboot to tools (not https link)

- README.md
Added PirateBox to OS Images and Network Presence Detector to Projects.
> PirateBox and Network Presence Detector added

- README.md
- [ X] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [ X] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [X ] includes a valid (https) link,
- [ X] includes a concise and on-topic description,
- [ X] mentions if there is only support some devices,
- [ X] is not a duplicate,
- [ X] has been added at the bottom of the appropriate category,
- [ X] is in the form of **Named Link - Description, seperated by commas.**
- [ X] ends with a dot.
> Added OctoPi

- README.md
- [ x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [ https not available] includes a valid (https) link,
- [ x] includes a concise and on-topic description,
- [x ] mentions if there is only support some devices,
- [ x] is not a duplicate,
- [x ] has been added at the bottom of the appropriate category,
- [x ] is in the form of **Named Link - Description, seperated by commas.**
- [x ] ends with a dot.
Kano OS description from developers at http://developers.kano.me/downloads/
> Add Kano OS to OS Images in README.md

- README.md
Added a project for running Wordpress project which includes MySQL database, PHP container, Caddy web server, and optional dynamic DNS container(s). All running in Docker containers.
> Add Wordpress using Docker project

- README.md
Added the subreddit /r/raspberry_pi_projects
> Added a community

- README.md
> Add tutorial how to build Raspberry Pi game console

- README.md
Sonic Pi is a coding synth that has a simple language optimal for teaching programming for beginners, but also a prefectly good tool for professional music producers. It has a really detailed and awesome [description](https://github.com/samaaron/sonic-pi/blob/master/README.md), which I won't even try to beat in this short message about it. I really enjoy playing around with it in my free time.
> Add Sonic Pi

- README.md
- [ https not available ] includes a valid (https) link,
Pi4j is a Java I/O library the Raspberry Pi
> Add Pi4j Project

- README.md
> :heavy-plus-sign: Added Wifi config generator tool.

- README.md
This tool can be used to play around with Raspbian, or to craft Raspberry Pi images that you can copy to an SD card.
> Tool to run Raspbian on QEMU with network access

- README.md
> Added RaspAP to the Tools list

- README.md
Switched the tutorial from Project --> Resources
> Added a tutorial to the Resources/Tutorials section

- README.md
> Add OpenWRT

- README.md
The previous one was not found.
> Fixed broken link for Snappy Ubuntu Core.

- README.md
- [+] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [+] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [+] includes a valid (https) link,
- [+] includes a concise and on-topic description,
- [+] mentions if there is only support some devices,
- [+] is not a duplicate,
- [+] has been added at the bottom of the appropriate category,
- [+] is in the form of **Named Link - Description, seperated by commas.**
- [+] ends with a dot.
> Added links to FreeBSD and NetBSD

- README.md
Add a cool project which can get your ARM device up and running Kubernetes in less than ten minutes into the project category.
> Add kubernetes-on-ARM into project category.

- README.md
Lumos
mimics the natural light of the sun as it passes overhead each day, generating bright blue light in the morning and warmer amber light in the evening in order to trigger the production of hormones like cortisol & melatonin which improves the user's sleep.
- [x ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
> Addition to the Projects List: Lumos

- README.md
Adding Android Things- Build connected devices for a wide variety of consumer, retail, and industrial applications.
> Adding Android Things

- README.md
:heavy-plus-sign: Added "Turn a Raspberry Pi into a Plex Media Server" to the Tutorials list
- [x ] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [ x] includes a valid (https) link,
- [x ] includes a concise and on-topic description,
- [x ] mentions if there is only support some devices,
- [ x] is not a duplicate,
- [x ] has been added at the bottom of the appropriate category,
- [x ] is in the form of **Named Link - Description, seperated by commas.**
- [x ] ends with a dot.
> Add Plex Media Server Tutorial

- README.md
> Project: Building timelapse using resin

- README.md
Add my robot bartender project to the list
> Add NALIVATOR-9000 to the Projects list

- README.md
> Fix typo in description

- README.md
P4wnP1 is a highly customizable USB attack platform, based on a low cost Raspberry Pi Zero or Raspberry Pi Zero W (required for HID backdoor).
> Added P4wnP1 under Tools Section

- README.md
> Update README.md (Gladys Project)

- README.md
This project is truly awesome and should definitely be listed here.
> Addition to the Projects List: Voice by Google

- README.md
CusDeb is a web UI for creating custom images
> Add CusDeb to the Tools List

- README.md
all projects offer ready made OS images for direct download
> Added OpenmediaVault; EZ-WifiBroadcast; DroneBridge

- README.md
- [+] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [+] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [+] includes a valid (https) link,
- [+] includes a concise and on-topic description,
- [+] mentions if there is only support some devices,
- [+] is not a duplicate,
- [+] has been added at the bottom of the appropriate category,
- [+] is in the form of **Named Link - Description, seperated by commas.**
- [+] ends with a dot.
> Added TrueOS

- README.md
CusDeb Beta 2 supports all Raspberry Pi models (except Raspberry Pi Zero W)
https://cusdeb.com/en/blog/2017/12/09/cusdeb-beta-2/
> Remove RPi2+ badge

- README.md
Found your list and thought my projects would qualify.  Both have extensive wiki help and very easy installation.  Thanks for your consideration
> speed camera and pi-timolo projects

- README.md
> :heavy-plus-sign: Added OpenHABian to the OS list

- README.md
> ✚ Added Hearing aid prototype to project list

- README.md
FabScan is an open source 3D laser scanner. The project started in 2010 at Germany's first FabLab in Aachen. The FabScan PI is the next generation of the FabScan 3D Laser Scanner.
> Added FabScanPi to OS section

- README.md
> Add Alpha to the tools list

- README.md
> Add Pieman to the Tools List

- README.md
> Added the project Rocket Show

- README.md
> Two new projects added to repo, RpiMotorLib and raspberrypi_tempmon

- README.md
Wifi management docker container for Pi 3.
> ✚ Added iotwifi - AP + Client wifi management. 

- README.md
> changed to new site

- README.md
> :heavy-plus-sign: Added Circle to the project list

- README.md
> Add : Tortipi tool

- README.md
Add Alpine Linux since Pieman supports it
> Updated description of Pieman

- README.md
> add sampler box

- README.md
> Added Processing IDE

- README.md
> add a tool to monitor downstream load on DOCSIS cable networks

- README.md
I have personally used these apps and found them very useful for ease of use with Pi.
> :heavy-plus-sign: Added list of useful android apps

- README.md
https://github.com/anshulahuja98/pi_payments
A payment module made on Raspberry based on RFID.
> Added my project pi_payments

- README.md
VNC Viewer, Turbo FTP, AndFTP
Android Links
> Added more app links

- README.md
> Added Articles and tutorials

- README.md
> add gentoo image description

- README.md
> :heavy_plus_sign: Added SARPi OS to the OS list

- README.md
> Added 2 projects to set up a lightning node for the bitcoin network

- README.md
> Add MoodleBox to the OS Images category

- README.md
> Update resinOS to balenaOS

- README.md
> Updated Models to include Pi 3 A+

- README.md
> Add a new section for swift programming topic in Resources

- README.md
[Raspbereum] - Run your own Ethereum node on a Raspberry Pi.
> Added [Raspbereum]

- README.md
> add project pi image capturer

- README.md
Introducing Bitcoin Bar, a physical LED Dashboard that displays important Bitcoin information such as Price, Total Bitcoins left to mine, Blocks until the reward is halved, Hash rate, etc. You can customize and choose what specific parameters you wish to display
> Bitcoin Tracker

- README.md
> Add Ubuntu Server distribution

- README.md
Auto-provisioned RPi cluster running K8S on bare-metal using a lot of tools and best practices.
> Project Ceil

- README.md
Etcher is now owned by Balena and its homepage domain has changed. Updated the link to reflect that
> Link correction. Etcher is under new ownership

- README.md
> Update link to HealthyPi

- README.md
Added Manjaro OS (ARM v8) to the OS image category.
> Manjaro to OS image list

- README.md
Added Smart Security Camera to the project list. :-)
> Added an item under projects.

- README.md
> Add FruitNanny to projects

- README.md
Added a new OS in the OS section
> Added LibreELEC

- README.md
> Add Orangetool

- README.md
> Add PiFmRds & PiAware

- README.md
Hi,
I'm the maintainer of [Gladys Assistant](https://github.com/GladysAssistant/Gladys/). Thanks for listing us! 
We changed domain and I wanted to update the domain here. You can check, old domain redirects to the new but still it's better to reference the new here :) 
> Update Gladys Assistant URL in README (domain of the project has changed)

- README.md
Hi, I hope that this tool will be of interest to some RPi users. Thanks!
> Add Hardened Kernel Builder for RPi to Tools

- README.md
Add Windows 10 ARM64, which is community supported. It can run on Raspberry Pi 3B/3B+/4B.
> Add an operating system

- README.md
Added the Coder for Raspberry Pi project and also moved couple of projects from Tools category.
> Added a project "Coder"

- README.md
This create a private full-featured OpenVPN/WireGuard VPN Server with a single(!!!) bash command.
> Add Tool "PiVPN"

- README.md
> Add tool 'Drago'

- README.md
> Added my Internet Chronometer repo to the list

- README.md
> Adding 'Atlas toolkit' as new tool.

- README.md
TwisterOS is a skinned version of rpiOS with box86 and retropie to help newbies get to learn Linux and Raspberry Pi
- [✔️] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [✔️] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [✔️] includes a valid (https) link,
- [✔️] includes a concise and on-topic description,
- [✔️] mentions if there is only support some devices,
- [✔️] is not a duplicate,
- [✔️] has been in the correct alphabetical order for its section,
- [✔️] is in the form of **Named Link - Description, seperated by commas.**
- [✔️] ends with a dot.
> Added Twister OS in OS'es

- README.md
> Add Rhasspy project

- README.md
> Add book "Control Your Home with Raspberry Pi"

- README.md
> Removed deprecated True Os

- README.md
RaspberryPi MorseCode Translator using Raspberry Pi
> Added Project "RasComm"

- README.md
- [x ] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [ x] includes a valid (https) link,
- [x ] includes a concise and on-topic description,
- [x ] mentions if there is only support some devices,
- [x ] is not a duplicate,
- [ x] is in the form of **Named Link - Description, seperated by commas.**
- [x ] ends with a dot.
> netflix tutorial

- README.md
> - Added RPi 400 to models list

- README.md
This adds Channels DVR Server's custom Raspberry Pi image.
> Add Channels DVR Server's custom image

- README.md
> Private photo cloud host on Raspberry Pi

- README.md
> add openSUSE info

- README.md
> Updated models to include Raspberry Pi Pico

- README.md
> Change WOA website to WoR

- README.md
Full-featured web-based dashboard interface to inspect and manage Raspberry Pi hardware and software with no extra software required
> Added project "Raspberry Pi Dashboard"

- README.md
> Add Haven to projects in readme

- README.md
> add stressberry

- README.md
> Update OpenWrt Raspberry Pi Documentation URL

- mkdocs.yml
> mkdocs.yml: Add light/dark mode switch

- README.md
> Add ndm, pistrong, and sdm to Tools section

- README.md
> Add usb-proxy to projects in README.md

- README.md
> Add Pico W

- README.md
> Added an iOS resource, then categorised the resources section by operating system

- README.md
Added the "Receiving GOES-16 Images on a Raspberry Pi" tutorial to the project section.
> Added the GOES-16 SDR Project

- README.md
Update dead links for Swift programming on Raspbian OS
- [ √] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [√ ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [ √] includes a valid (https) link,
- [ √] includes a concise and on-topic description,
- [√ ] mentions if there is only support some devices,
- [ √] is not a duplicate,
- [ √] has been in the correct alphabetical order for its section,
- [ √] is in the form of **Named Link - Description, separated by commas.**
- [ √] ends with a dot.
> Update dead links for Swift programming on Pi

- README.md
Hello - suggest an addition to the Articles section of this Awesome List.
- [10 Years of Raspberry Pi](https://kandi.openweaver.com/collections/educational-service-providers/10-years-of-raspberry-pi) - collections on 10 Years of Raspberry Pi, showcasing the most popular libraries across hobbyist uses cases, home automation, IoT, OS and utilities.
Can someone review and provide a feedback.
> Addition to Articles section

- README.md
> add rpi-cookstrap

- README.md
> Add KonstaKANG

- README.md
> Add Armbian

- README.md
> Add official mastodon profile #HSFDPMUW

- README.md
> Add FreedomBox

- README.md
> Add Debian

- README.md
> Add Mailsail OS

- README.md
> Add Raspberry Pi Setup Project

- README.md
Added Raspberry Pi 5 to list of models
> Add Raspberry Pi 5 to list of models

- README.md
> Added TelepI

- README.md
Now replaced with a working link
> Nextcloud link was dead

- README.md
PiKISS is a bunch of scripts with menu to make your life easier.
> Add PiKISS

- README.md
> Add moOde Audio Player

- README.md
> feat: PiGo android app added

- README.md
> Adding library Display_Lib_RPI to project list

- README.md
- [ x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/main/CONTRIBUTING.md).
- [ x] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- [ x] includes a valid (https) link,
- [ x] includes a concise and on-topic description,
- [ x] mentions if there is only support some devices,
- [ x] is not a duplicate,
- [ x] has been in the correct alphabetical order for its section,
- [x ] is in the form of **Named Link - Description, separated by commas.**
- [ x] ends with a dot.
> Added Raspberry Pi Monitor Dashboard tool

- README.md
Add PiFi for Raspberry Pi 4 and 5 to OS Images
> Add PiFi to OS Images

- README.md
> Add Pi 500 to the hardware list
